# Generated by Django 3.2 on 2021-06-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_difficulty', models.CharField(choices=[('easy', 'EASY'), ('usually', 'USUALLY'), ('difficult', 'DIFFICULT')], max_length=40)),
            ],
            options={
                'verbose_name_plural': '과목 관리',
            },
        ),
    ]
